### ISSUE TITLE
CommonCryptor.h?

### ISSUE THREAD

**Issue by Qwertylex** [amraboelela/CommonCrypto#2]
no CommonCryptor.h?

https://github.com/Apple-FOSS-Mirror/CommonCrypto/blob/master/CommonCrypto/CommonCryptor.h

**Comment by amraboelela** [comment]
here

https://github.com/amraboelela/CommonCrypto/blob/master/CommonCrypto/CommonCrypto.h

**Comment by Qwertylex** [comment]
thanks
